# Generated by Django 5.2.14 on 2026-06-23 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, help_text='사용자 나이 (추천 알고리즘 청년 우대 기준)', null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_range', models.CharField(choices=[('low', '500만 미만'), ('mid', '500만~2000만'), ('high', '2000만~5000만'), ('vhigh', '5000만 이상')], help_text='자산 규모', max_length=10)),
                ('interest_assets', models.JSONField(default=list, help_text="관심 자산 리스트 (['deposit', 'stock', 'crypto', 'gold'])")),
                ('risk_type', models.CharField(choices=[('safe', '안정형 (원금 보전)'), ('neutral', '중립형 (적당한 수익)'), ('aggressive', '공격형 (고수익)')], help_text='투자 성향', max_length=15)),
                ('monthly_budget', models.CharField(choices=[('low', '10만 미만'), ('mid', '10~50만'), ('high', '50~100만'), ('vhigh', '100만 이상')], help_text='월 여유자금', max_length=10)),
                ('is_onboarded', models.BooleanField(default=False, help_text='온보딩 완료 여부 (False일 경우 서비스 이용 제한 및 리다이렉트)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
