# Generated by Django 5.2.14 on 2026-06-08 01:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinBuzz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coin_symbol', models.CharField(max_length=20)),
                ('news_count', models.IntegerField(default=0)),
                ('volume_24h', models.BigIntegerField(default=0)),
                ('buzz_score', models.FloatField(default=0.0)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coin_buzz',
            },
        ),
        migrations.CreateModel(
            name='CoinSentiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coin_symbol', models.CharField(max_length=20)),
                ('positive_score', models.FloatField(default=0.0)),
                ('neutral_score', models.FloatField(default=0.0)),
                ('negative_score', models.FloatField(default=0.0)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coin_sentiment',
            },
        ),
        migrations.CreateModel(
            name='WatchlistCoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coin_symbol', models.CharField(max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_coins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watchlist_coins',
                'unique_together': {('user', 'coin_symbol')},
            },
        ),
    ]
