# Generated by Django 5.2.14 on 2026-06-24 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('SAVINGS', '예적금'), ('STOCKS', '주식'), ('CRYPTO', '크립토')], max_length=20)),
                ('asset_code', models.CharField(max_length=100)),
                ('asset_name', models.CharField(max_length=100)),
                ('brokerage', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(choices=[('KRW', '원화'), ('USD', '달러')], default='KRW', max_length=3)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('accumulated_return', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('memo', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
