# Generated by Django 5.2.14 on 2026-06-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='asset_type',
            field=models.CharField(choices=[('SAVINGS', '예적금'), ('STOCKS', '주식'), ('CRYPTO', '크립토'), ('CASH', '현금')], max_length=20),
        ),
    ]
