# Generated by Django 5.2.14 on 2026-06-14 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('food', '식비'), ('cafe', '카페'), ('transport', '교통'), ('shopping', '쇼핑'), ('convenience', '편의점'), ('health', '의료/건강'), ('culture', '문화/여가'), ('telecom', '통신'), ('subscription', '구독'), ('rent', '월세'), ('transfer', '이체'), ('etc', '기타')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('expense', '지출'), ('income', '수입'), ('transfer', '이체')], default='expense', max_length=10)),
                ('category', models.CharField(choices=[('food', '식비'), ('cafe', '카페'), ('transport', '교통'), ('shopping', '쇼핑'), ('convenience', '편의점'), ('health', '의료/건강'), ('culture', '문화/여가'), ('telecom', '통신'), ('subscription', '구독'), ('rent', '월세'), ('transfer', '이체'), ('etc', '기타')], default='etc', max_length=20)),
                ('is_fixed', models.BooleanField(default=False)),
                ('transacted_at', models.DateTimeField()),
                ('is_settle_target', models.BooleanField(default=False)),
                ('is_settled', models.BooleanField(default=False)),
                ('settle_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('original_type', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumption.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transacted_at'],
            },
        ),
    ]
