# Generated by Django 5.2.14 on 2026-06-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='settle_people_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='settle_per_person',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
